// Generated by CoffeeScript 1.6.2
var env, fs, path, settings, settings_cache;

fs = require('fs');

path = require('path');

settings_cache = null;

env = process.env.NODE_ENV || 'development';

console.log("Loading and parsing application settings for env: " + env);

if (env === 'development' || env === 'test' || env === 'production') {
  settings = require(path.join(process.cwd(), 'settings', 'settings.json'));
  settings_cache = settings[env];
} else {
  console.log("NODE_ENV not correctly set");
}

exports.get = function(key, callback) {
  return settings_cache[key];
};
