// Generated by CoffeeScript 1.6.2

(function() {
  var env, fs, path, settings, settings_cache;

  fs = require('fs');

  path = require('path');

  settings_cache = null;

  env = process.env.NODE_ENV;

  console.log("Loading and parsing application settings for env: " + env);

  if (env === 'development' || env === 'test' || env === 'production') {
    settings = require(path.resolve(__dirname, 'settings', 'settings.json'));
    settings_cache = settings[env];
  } else {
    console.log("NODE_ENV not correctly set");
  }

  exports.get = function(key, callback) {
    return settings_cache[key];
  };

}).call(this);
