// Generated by CoffeeScript 1.4.0
var fs, path, settings_cache,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

fs = require('fs');

path = require('path');

settings_cache = null;

exports.get = function(key, callback) {
  return settings_cache[key];
};

exports.load_settings = function(env) {
  var settings, settings_path;
  console.log("Loading and parsing application settings for env".info, env.help);
  if (env === 'development' || env === 'test' || env === 'production') {
    settings = require(path.join(process.cwd(), 'settings', 'settings.json'));
    settings_cache = settings[env];
  } else {
    if (__indexOf.call(env, '.') >= 0) {
      env = env.split('.');
      settings_path = env.join('/');
      env = env[env.length - 1];
    } else {
      settings_path = env;
    }
    try {
      settings = require(path.join(process.cwd(), 'settings', "" + settings_path + ".coffee"));
    } catch (e) {
      console.log(e.toString().error);
      process.exit(1);
    }
    try {
      settings = JSON.parse(settings[env]);
    } catch (e) {
      console.log("Settings must be in valid JSON format".error);
    }
    return settings_cache = settings;
  }
};
